### PR TITLE
Fix enableCreationOfFiles can't disable. And support more language message.yum

### PR DESCRIPTION
**Pull request by ChrisLv-CN**
1、Change itemRegister to LinkedHashMap.
2、Fix enableCreationOfFiles can't disable.
3、Support SunLight-Core's economy.

### CODE REVIEW

**Comment by ZombieStriker** [comment]
Hello ChrisLV-CN,

These changes will be added in the next update.

**Comment by ChrisLv-CN** [comment]
Can you consider changing the control like this:
if the enableIronSightsON_RIGHT_CLIKC is false (default):
- [LMB] SingleFire
- [RMB] SingleFire / AutoFire(if the Waepon has Automatic)
- [Shift-Hold] Enable Iron Sights 
- [F] Always Reload
if the enableIronSightsON_RIGHT_CLIKC is true:
- [LMB] SingleFire / AutoFire(if the Weapon has Automatic)
- [RMB] Enable Iron Sights
- [Shift-Hold] + [LMB] SingleFire
- [F] Always Reload 
I can't read the code in this part, so I can only make this suggestion.

**Comment by ChrisLv-CN** [comment]
!!! WARNING !!! This last submission was ONLY TESTED by MC1.14.4(Paper-167), almost REWRITING the logic of all guns, including aiming, loading, automatic shooting, burst mode, etc.

Gun attributes modify:
- All gun can use AutoFire-Mode. Including Burst-Fire mode charger.
- Only has "enableBetterModelScopes=true" will use IronSight like Sniper rifle.
- Burst-Fire mode charger only can shoot 1 bullet in one shot, "bullets-per-shot" use control how many times to shot in one pull the trigger.

Global modify:
- If player offhand holding something like shield, now will put it to backpack if enable IronSights, or drop it if backpack full, including shopping/crafting.
- RMB click will shot if "enableReloadOnlyWhenSwapToOffhand=true" and "IronSightsOnRightClick=false".
- "SwapSneakToSingleFile=true" will make Gun's AutoFire lose its effect.
- Try to drop a gun in aiming, now will cancel aiming, and clean all illegal IronSights.
- Lore will show the charger type use Message_xx.yml.
- The store now has a new control item that controls whether items on the player can be clicked to shop/craft.
- More message item about gun's Help lore.

Last, I very like this plugin, I hope these things are helpful.
Forgive my Chinglish. This is already my limit. :)

**Comment by ChrisLv-CN** [comment]
I found something, actually don't need to CREATE an IronSight and swap hand. Just need to add a new charged model in the resource package.
crossbow.json :
...
{"predicate": { "custom_model_data": 20 }, "model": "item/awp" },
{"predicate" : {"custom_model_data": 20, "charged": 1 }, "model": "item/awp2"},
...
Use the SAME ID, different charging status.
Now he will change the model between charged(awp2) and undercharged(awp), and raise he hand to aim.
It's so exciting that I feel like I've done all my work in vain. 
T^T

**Comment by ChrisLv-CN** [comment]
Hello ZombieStriker.
I would like to submit an application to you to build a new project based on this project. 
I want to kill many old versions of the logic, which may lead to the impossibility of merging and can only work on the new version 1.14. 
If you have any view, please email me. 
My email address is 12737@live.com.

**Comment by Lorenzo0111** [comment]
This is very outdated, if you want you can recreate it and I’ll check it

**Pull request closed without merging**
